### ISSUE TITLE
Upgrades to methadone to keep it up to date.

### ISSUE THREAD

**Issue by nisevi** [davetron5000/methadone#116]
Hey @davetron5000 are you interested in maintaining this project? I think that what you have built is pretty cool :rocket: and I would like to contribute to the project :grinning: . Do you use something like PivotaTrakcer/Jira/Trello/Zenhub for creating iterations to deliver features or just to keep the project up to date? Maybe an slack channel?

Please let me know in which way could I help to keep this project up to date :grinning:

**Comment by nisevi** [comment]
Hey @davetron5000, I was thinking something like an integration with [dependabot](https://dependabot.com) to keep gem versions up to date, and once that is setup, to have minor releases with the upgrades that were done.

Also since you have an integration with [TravisCI](https://travis-ci.org/davetron5000/methadone) we could add [CodeClimate](https://codeclimate.com) for giving to the project an overview of the code. This integration also allows you to create issues based on improvements that you can do to the code. By creating this issues, you are inviting the community to collaborate in your project since sometimes there are just minor adjustments that can be done to the code.

Zenhub is an option that I like when you have to integrate a management tool with github :grinning:  so anyone will be able to see the issues the project has and make pull requests based on those issues that were created :grinning: 

We could add a contributions guide line, and a code of conduct :smiley: 

What do you think?

**Comment by davetron5000** [comment]
Hey, sorry for the delay…was on vacation.

I'm not in favor of CodeCilmate, as it incentivizes churn in the codebase to game the grading system and doesn't really promote better code.  I also don't need a project management tool as the project is currently stable/maintenance and not undergoing a lot of new feature development.  If people want to see the issues, they can use the issues feature of GitHub (unless I'm not understanding what Zenhub does).

Dependabot is a nice idea, but in the past I've used it and it didn't really work as I'd hoped.  It just created a lot of extra work.

A COC, though…yes.  I'm surprised I don't have one as I thought I'd made one for this repo, but I guess there isn't one :(

**Comment by nisevi** [comment]
Hi there!! Nice to hear back from you. Yup I get what you mean :+1: 

All the best :rocket: and again awesome job with this gem :+1:
