### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by daveallen** [davetron5000/methadone#128]
Not really an issue, but a question.  How would you do bash completion with methadone?

**Comment by davetron5000** [comment]
Of the CLI options?  not sure…I hadn't thought about it.  My other gem (GLI) has a command that can output the available subcommands in a way that favors bash completion.  We could do something like that here, like `your_app --bash-completion` and it lists out the available options?  Just guess here, as I haven't done this for cli options before

**Comment by daveallen** [comment]
I was actually looking at GLI.  So with that I can get the commands to tab complete?  I also want to get a listing of files from a specific directory to obtain another list and another list from objects I can get from a server.  I just found this which does more than tab completion. but I don't need the other stuff.  
https://github.com/saveriomiroddi/simple_scripting/#simplescriptingtabcompletion

**Comment by davetron5000** [comment]
Yeah, not sure how methadone could be helpful—that sounds like a very specific use case.  You could always write your methadone app to provide those completion targets I guess?

**Comment by daveallen** [comment]
Yeah, I think that is what I am going to do.  Thanks!!
