### ISSUE TITLE
repo rename optparse-plus -> methadone?

### ISSUE THREAD

**Issue by monperrus** [davetron5000/methadone#139]
Hi @davetron5000!

[Googling methadone](https://www.google.com/search?q=methadone+ruby), finding [jshort/methadone](https://github.com/jshort/methadone), realizing it's probably an outdated fork.

Google and me are confused by this repo being named `optparse-plus`, 

- with links inside the repo to `davetron5000/methadone` ([link](https://github.com/davetron5000/methadone/blob/074daa943ceccaf32fe67e4141b95f0c2d01e3fe/CHANGES.md?plain=1#L9))
- with forks being named methadone, eg [jshort/methadone](https://github.com/jshort/methadone)
- with the [rubygems page](https://rubygems.org/gems/methadone) pointing to https://github.com/davetron5000/methadone

It's considered a good practice in software supply chain to name the repo after the package.

What about naming this repo `methadone`?

Thanks!

**Comment by davetron5000** [comment]
The name was changed a while back.  There was a link to that in the README, but I have now made it more prominent.

Of note, I'm not a supplier, so I'm not part of any supply chain.  I appreciate that someone may want to use this for something important and that the name change may be confusing, but it is documented to the best of my ability.

**Comment by monperrus** [comment]
ack, thanks!
