### ISSUE TITLE
Don't expose user to bugs in RubyGems if possible 

### ISSUE THREAD

**Issue by NeilW** [davetron5000/methadone#85]
The bundle gem command fails when run via methadone, but doesn't when run on its own.

Step to reproduce:
- Install fresh cloud instance of Ubuntu Trusty from ubuntu cloud archives.
- sudo apt-get update
- sudo apt-get install language-pack-en ruby git
- sudo gem install --no-ri --no-rdoc methadone
- methadone --log-level=debug --readme --rspec --license gplv3 app_name

Which gives:
Creating project for gem app_name
Executing 'bundle gem app_name --no-color'
stdout output of 'bundle gem app_name --no-color':       create  app_name/Gemfile
      create  app_name/Rakefile
      create  app_name/LICENSE.txt
      create  app_name/README.md
      create  app_name/.gitignore
      create  app_name/app_name.gemspec
      create  app_name/lib/app_name.rb
      create  app_name/lib/app_name/version.rb
Initializing git repo in /home/ubuntu/app_name
Invalid gemspec in [app_name.gemspec]: undefined method `prerelease?' for "0.0.1":String
undefined method`name' for nil:NilClass

Yet running the command on the command prompt gives:

ubuntu@srv-t787y:~$ bundle gem app_name --no-color
      create  app_name/Gemfile
      create  app_name/Rakefile
      create  app_name/LICENSE.txt
      create  app_name/README.md
      create  app_name/.gitignore
      create  app_name/app_name.gemspec
      create  app_name/lib/app_name.rb
      create  app_name/lib/app_name/version.rb
Initializing git repo in /home/ubuntu/app_name
ubuntu@srv-t787y:~$

**Comment by davetron5000** [comment]
Closing as old/won't fix.  This is 4+ years old and I only have bandwidth to support supported rubies.
