### ISSUE TITLE
Options for displaying version info

### ISSUE THREAD

**Issue by lebogan** [davetron5000/methadone#90]
Is it possible to change the code so the version only shows when specifically called:
  my-app --version
and not show up when --help is used?

Thanks for this great gem. 
Yes, I did buy the book at version 2:-)

**Comment by davetron5000** [comment]
Have you tried

```ruby
version "1.2.3", compact: true
```

That should do what you want.  Let me know if not.

And thanks for buying the book :)

**Comment by davetron5000** [comment]
Re-open if you were looking for something else.  If you have sample desired output, that'll help.  Shouldn't be hard to provide alternates.
