### ISSUE TITLE
How do I get at the log-level?

### ISSUE THREAD

**Issue by blysik** [davetron5000/methadone#94]
I want to key an if statement off of --log-level debug being set.

I can't quite figure out what my code should be looking at.

If I use @@logger.level == 0, it works when debug is set.  But if I don't set debug, it complains @@logger.level doesn't exist.

**Comment by davetron5000** [comment]
If you are using [`use_log_level_option`](https://github.com/davetron5000/methadone/blob/master/lib/methadone/cli_logging.rb#L103), you should be able to get the log level via `logger.level`.

This assumes you have mixed-in `CLILogging`.

`@@logger` isn't set by methadone, so I'm not sure why it ever works for you

**Comment by davetron5000** [comment]
Re-open if you weren't able to get what you needed from `logger.level`

**Comment by blysik** [comment]
Sorry, forgot to update this.  It works great.  Simply doing:

```
if logger.level == 0
  faraday.response :logger
end
```

So I get more debugging out of faraday, if I set debug in methadone.  Thanks again.
