### ISSUE TITLE
including Methadone::CLILogger in class gives `wrong argument type Class`

### ISSUE THREAD

**Issue by gnowxilef** [davetron5000/methadone#97]
this is following the instructions given here: http://naildrivin5.com/methadone/rdoc/classes/Methadone/CLILogging.html

**Comment by sch0rsch** [comment]
There is a simple typo. Use Methadone::CLILogging instead of Methadone::CLILogger. See pull request #98

**Comment by davetron5000** [comment]
Should be fixed in latest release and update on the RDoc.  Thanks @sch0rsch for the fix!
